Chart: chart/ms-validate-user
ChartNamespace: ortelius
DockerRepo: quay.io/ortelius/ms-validate-user
DockerSha: 1514e7b6b93ccf0a2bb0dc3fe4622b4ec867f070528376547865c738c073f93a
DockerTag: deploy-v10.0.0.28-g88d4fca
EXT: sh
GitBranch: deploy
GitCommit: 88d4fca
GitRepo: ortelius/ortelius-ms-validate-user
GitTag: deploy
GitUrl: git@github.com:ortelius/ortelius-ms-validate-user.git
RE_PHYSICAL_HOSTNAME: localhost
RE_PHYSICAL_SERVER: localhost
aks:
  admin: true
  certificate: /root/.ssh/aks.pem
  cluster: cluster2-aks
  resourcegroup: cluster1-rg
application: ortelius-devops;10_0_10
builddate: Wed Dec  1 23:39:57 UTC 2021
buildid: 8f35a209-cf7d-4c36-b7bb-f58aeb500864
buildurl: https://console.cloud.google.com/cloud-build/builds/8f35a209-cf7d-4c36-b7bb-f58aeb500864?project=eighth-physics-169321
chart: chart/ms-validate-user
chartnamespace: ortelius
chartpublish: Y
component: ms-validate-user;deploy;v10_0_0_28_g88d4fca
dockerrepo: quay.io/ortelius/ms-validate-user
dockersha: 1514e7b6b93ccf0a2bb0dc3fe4622b4ec867f070528376547865c738c073f93a
dockertag: deploy-v10.0.0.28-g88d4fca
dropzone: /tmp/tdm.1463.10
environment: aks-cluster
gitcommit: 88d4fca
gitrepo: ortelius/ortelius-ms-validate-user
gittag: deploy
giturl: git@github.com:ortelius/ortelius-ms-validate-user.git
image:
  pullPolicy: Always
kubectl_context: cluster2-aks-admin
server_hostname: localhost
server_name: localhost
