BuildNumber: 0
Chart: chart/ms-validate-user
ChartNamespace: ortelius
CustomAction: GLOBAL.HelmChart
DockerRepo: quay.io/ortelius/ms-validate-user
DockerSha: ebba0d345aa1
DockerTag: deploy-v10.0.0.54-g58ed74d
EXT: sh
GitBranch: deploy
GitCommit: 58ed74d
GitRepo: ortelius/ortelius-ms-validate-user
GitTag: deploy
GitUrl: https://github.com/ortelius/ortelius-ms-validate-user.git
RE_PHYSICAL_HOSTNAME: localhost
RE_PHYSICAL_SERVER: localhost
aks:
  admin: true
  cluster: cluster2-aks
  resourcegroup: cluster1-rg
application: ortelius;10_0_0
builddate: Thu Mar 17 16:32:35 2022
buildid: 4005f572-4f22-4920-933a-0616812f8584
buildurl: https://console.cloud.google.com/cloud-build/builds/4005f572-4f22-4920-933a-0616812f8584?project=eighth-physics-169321
chart: chart/ms-validate-user
chartnamespace: ortelius
component: ms-validate-user;deploy;v10_0_0_54_g58ed74d
dockerrepo: quay.io/ortelius/ms-validate-user
dockersha: ebba0d345aa1
dockertag: deploy-v10.0.0.54-g58ed74d
dropzone: /tmp/tdm.1543.6
environment: aks-cluster
gitcommit: 58ed74d
gitrepo: ortelius/ortelius-ms-validate-user
gittag: deploy
giturl: https://github.com/ortelius/ortelius-ms-validate-user.git
kubectl_context: cluster2-aks-admin
server_hostname: localhost
server_name: localhost
