apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rpt-env2app.name" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "rpt-env2app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "rpt-env2app.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        {{- with .Values.image }}
        image: "{{ .repository }}{{- if .digest }}@{{ .digest }}{{- else }}:{{ .tag | default $.Chart.AppVersion }}{{- end}}"
        {{- end }}
        imagePullPolicy: Always
        {{- with .Values.service }}
        ports:
          - name: {{ .portName }}
            containerPort: {{ .exposedPort }}
            protocol: TCP
        {{- end }}
        {{- with .Values.resources }}
        resources: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.envVars }}
        env:
          {{- range $k, $v := . }}
          - name: {{ $k }}
            value: {{ $v | quote }}
          {{- end }}
        {{- end }}
        {{- with .Values.secrets }}
        envFrom:
          {{- range $k, $v := . }}
          - secretRef:
              name: {{ $k }}
          {{- end }}
        {{- end }}
        {{- with .Values.livenessProbe }}
        livenessProbe: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe: {{- toYaml . | nindent 10 }}
        {{- end }}
