apiVersion: v1
kind: Service
metadata:
  name: {{ include "rpt-env2app.name" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "rpt-env2app.name" . }}
  ports:
  {{- with .Values.service }}
  - name: {{ .portName }}
    targetPort: {{ .targetPort }}
    port: {{ .exposedPort }}
    nodePort: {{ .nodePort }}
  {{- end }}

