---
name: Build/Push Image and Release Charts

on:
  pull_request:
    paths-ignore:
      - "chart/**/Chart.yaml"
      - "chart/**/values.yaml"
  push:
    branches:
      - main
    paths-ignore:
      - "chart/**/Chart.yaml"
      - "chart/**/values.yaml"

permissions: read-all

jobs:
  setenv:
    uses: ortelius/ms-setenv-action/.github/workflows/workflow-set-env.yml@90316c8abab18fbedca2ec1eafe547608d9d11a1
    with:
      gh_head_ref: ${{ github.head_ref }}
      gh_ref_name: ${{ github.ref_name }}
      gh_event_repo_name: ${{ github.event.repository.name }}
      gh_sha: ${{ github.sha }}
      gh_repo: ${{ github.repository }}
      gh_run_number: ${{ github.run_number }}

  release:
    runs-on: ubuntu-latest
    needs: setenv

    outputs:
      digest: ${{ steps.release.outputs.digest }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Image Releaser
        id: release
        uses: ortelius/ms-release-action@8d3e173e28e5614e6d26f43d447a5c12baf384f2 # v1.0.0
        with:
          gh_repository_owner: ${{ github.repository_owner }}
          gh_event_name: ${{ github.event_name }}
          gh_ref: ${{ github.ref }}
          registry: ${{ needs.setenv.outputs.registry }}
          QUAY_USERID: ${{ secrets.QUAY_USERID }}
          QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
          image_repo_tag: ${{ needs.setenv.outputs.image_repo_tag }}

  trivy:
    runs-on: ubuntu-latest
    needs: [setenv, release]

    permissions:
      security-events: write
      statuses: write

    if: ${{ github.repository_owner == 'ortelius' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout
        id: checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@1f0aa582c8c8f5f7639610d6d38baddfea4fdcee # master
        with:
          image-ref: ${{ needs.setenv.outputs.image_repo_tag }}
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@168b99b3c22180941ae7dbdd5f5c9678ede476ba # v2.2.7
        if: always()
        with:
          sarif_file: "trivy-results.sarif"

  helm:
    runs-on: ubuntu-latest
    needs: [setenv, release]

    permissions:
      contents: write

    if: ${{ github.repository_owner == 'ortelius' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Helm Chart Releaser
        uses: ortelius/ms-cr-action@d98a4163765db41dbc8159f3a31f30f77bbe23bd # v1.2.0
        with:
          gpg_keyring_base64: ${{ secrets.GPG_KEYRING_BASE64 }}
          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
          gpg_key: ${{ secrets.GPG_KEY }}
          gh_token: ${{ secrets.HELM_INDEXER_TOKEN }}
          gh_handle: ${{ needs.setenv.outputs.gh_handle }}
          chart: chart/${{ needs.setenv.outputs.compname }}
          chart_version: ${{ needs.setenv.outputs.chart_version }}
          image_repository: ${{ needs.setenv.outputs.image_repository }}
          image_tag: ${{ needs.setenv.outputs.image_tag }}
          image_digest: ${{ needs.release.outputs.digest }}

      - name: Trigger Rebuild of Main Chart
        uses: benc-uk/workflow-dispatch@798e70c97009500150087d30d9f11c5444830385 # v1.2.2
        with:
          workflow: generate-main-chart.yml
          repo: ortelius/ortelius-charts
          token: ${{ secrets.HELM_INDEXER_TOKEN }}

  sbom:
    runs-on: ubuntu-latest
    needs: [setenv, release]

    if: ${{ github.repository_owner == 'ortelius' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: SBOM
        uses: ortelius/ms-sbom-action@78faa3aadef42708432a337fa2953a82ddfd2512 # v1.0.0
        with:
          dhpass: ${{ secrets.DHPASS }}
          dhurl: ${{ needs.setenv.outputs.dhurl }}
          dhuser: ${{ secrets.DHUSER }}
          compname: ${{ needs.setenv.outputs.compname }}
          chart_version: ${{ needs.setenv.outputs.chart_version }}
          git_branch: ${{ needs.setenv.outputs.branch }}
          image_digest: ${{ needs.release.outputs.digest }}
          image_repo_tag: ${{ needs.setenv.outputs.image_repo_tag }}
          image_repository: ${{ needs.setenv.outputs.image_repository }}
          image_tag: ${{ needs.setenv.outputs.image_tag }}
          image_version: ${{ needs.setenv.outputs.image_version }}
