---
name: Build/Push Image and Release Charts

on:
  pull_request:
    paths-ignore:
      - "chart/**/Chart.yaml"
      - "chart/**/values.yaml"
  push:
    branches:
      - main
    paths-ignore:
      - "chart/**/Chart.yaml"
      - "chart/**/values.yaml"

permissions: read-all

jobs:
  setenv:
    uses: ortelius/workflow-toolkit/.github/workflows/env-config-workflow.yml@main
    with:
      gh_head_ref: ${{ github.head_ref }}
      gh_ref_name: ${{ github.ref_name }}
      gh_event_repo_name: ${{ github.event.repository.name }}
      gh_sha: ${{ github.sha }}
      gh_repo: ${{ github.repository }}
      gh_run_number: ${{ github.run_number }}
