---
name: Build/Push Image and Release Charts

on:
  pull_request:
    paths-ignore:
      - "chart/**/Chart.yaml"
      - "chart/**/values.yaml"
  push:
    branches:
      - main
    paths-ignore:
      - "chart/**/Chart.yaml"
      - "chart/**/values.yaml"

permissions: read-all

jobs:
  setenv:
    uses: ortelius/workflow-toolkit/.github/workflows/env-config-workflow.yml@chore/standalone-workflow
    with:
      gh_head_ref: ${{ github.head_ref }}
      gh_ref_name: ${{ github.ref_name }}
      gh_event_repo_name: ${{ github.event.repository.name }}
      gh_sha: ${{ github.sha }}
      gh_repo: ${{ github.repository }}
      gh_run_number: ${{ github.run_number }}

  release:
    uses: ortelius/workflow-toolkit/.github/workflows/container-release-workflow.yml@chore/standalone-workflow
    needs: setenv
    with:
      gh_repository_owner: ${{ github.repository_owner }}
      gh_event_name: ${{ github.event_name }}
      gh_ref: ${{ github.ref }}
      registry: ${{ needs.setenv.outputs.registry }}
      image_repo_tag: ${{ needs.setenv.outputs.image_repo_tag }}
    secrets:
      QUAY_USERID: ${{ secrets.QUAY_USERID }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

  trivy:
    permissions:
      security-events: write
      statuses: write
    uses: ortelius/workflow-toolkit/.github/workflows/trivy-scan-workflow.yml@chore/standalone-workflow
    needs: [setenv, release]
    with:
      gh_repository_owner: ${{ github.repository_owner }}
      gh_event_name: ${{ github.event_name }}
      gh_ref: ${{ github.ref }}
      image_repo_tag: ${{ needs.setenv.outputs.image_repo_tag }}

  helm:
    permissions:
      contents: write
    uses: ortelius/workflow-toolkit/.github/workflows/helm-release-workflow.yml@chore/standalone-workflow
    needs: [setenv, release]
    with:
      gh_repository_owner: ${{ github.repository_owner }}
      gh_event_name: ${{ github.event_name }}
      gh_ref: ${{ github.ref }}
      gh_handle: ${{ needs.setenv.outputs.gh_handle }}
      chart: chart/${{ needs.setenv.outputs.compname }}
      chart_version: ${{ needs.setenv.outputs.chart_version }}
      image_repository: ${{ needs.setenv.outputs.image_repository }}
      image_tag: ${{ needs.setenv.outputs.image_tag }}
      image_digest: ${{ needs.release.outputs.digest }}
    secrets:
      GPG_KEYRING_BASE64: ${{ secrets.GPG_KEYRING_BASE64 }}
      GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      GPG_KEY: ${{ secrets.GPG_KEY }}
      gh_token: ${{ secrets.HELM_INDEXER_TOKEN }}

  sbom:
    runs-on: ubuntu-latest
    needs: [setenv, release]

    if: ${{ github.repository_owner == 'ortelius' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: SBOM
        uses: ortelius/ms-sbom-action@78faa3aadef42708432a337fa2953a82ddfd2512 # v1.0.0
        with:
          dhpass: ${{ secrets.DHPASS }}
          dhurl: ${{ needs.setenv.outputs.dhurl }}
          dhuser: ${{ secrets.DHUSER }}
          compname: ${{ needs.setenv.outputs.compname }}
          chart_version: ${{ needs.setenv.outputs.chart_version }}
          git_branch: ${{ needs.setenv.outputs.branch }}
          image_digest: ${{ needs.release.outputs.digest }}
          image_repo_tag: ${{ needs.setenv.outputs.image_repo_tag }}
          image_repository: ${{ needs.setenv.outputs.image_repository }}
          image_tag: ${{ needs.setenv.outputs.image_tag }}
          image_version: ${{ needs.setenv.outputs.image_version }}
